services:
  smee:
    build: .
    image: smee2image:latest
    ports: 
      - "5000:5000"
    container_name: smee2

  nginx:
    image: nginx:alpine
    ports: 
      - "9000:80"
    container_name: nginx

  



