http {

    # default website, on port 80
    server {
        listen 80 default_server;
        server_name webhookrelay.com;
        location /webhook {
            proxy_pass http://smee2:5000;
        }

        location /tunnel {
            proxy_pass http://smee2:5000;
        }
    }
}

events { }

